# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-13 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20160911_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=stories.models.upload_location, width_field='width_field'),
        ),
    ]
