# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-18 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20160912_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=stories.models.upload_location),
        ),
    ]
